### PR TITLE
Ticket types and sponsors

### PR DESCRIPTION
**Pull request by freshtonic**

### CODE REVIEW

**Comment by freshtonic** [comment]
Home page now looks like:

image

Get Ticket links to new section:

image

**Comment by freshtonic** [comment]
So with the new ticket type, the homepage was getting crowded.

The background and logo are no longer fixed.

**Comment by keithpitty** [comment]
@freshtonic should we say something about how women who have already purchased a ticket at full price should go about applying for a $70 refund?

**Comment by freshtonic** [comment]
@keithpitty I can add that

**Comment by lengarvey** [comment]
I'm happy with this, we need to be careful not to launch this change until after we have the ti.to tickets available for women though.

**Comment by lengarvey** [comment]
Also let's launch it on Tuesday so coincide with RoRo.

**Comment by freshtonic** [comment]
@keithpitty I've added a note about existing ticket holders being able to apply for the discount.

@lengarvey cool, sounds like a plan.

**Pull request merged**
